"""Transparency label generation.

Maps a confidence (AI-likelihood, 0..1) to one of three plain-language labels a
reader would see on the platform. The text differs by band, not just the number,
and every variant states it is an automated estimate and points to appeal.
"""

from scoring import attribution_for

_LABELS = {
    "likely_ai": {
        "headline": "Likely AI-generated",
        "icon": "AI",
        "detail": (
            "Our analysis found strong signs that this text was produced by an AI "
            "system rather than written by a person. This is an automated estimate, "
            "not a certainty, and detection can be wrong. If you believe you wrote "
            "this yourself, you can appeal this label."
        ),
    },
    "uncertain": {
        "headline": "Uncertain origin",
        "icon": "?",
        "detail": (
            "Our analysis could not confidently tell whether this text was written "
            "by a person or generated by AI. We are showing this honestly rather "
            "than guessing. The creator is welcome to add context or appeal."
        ),
    },
    "likely_human": {
        "headline": "Likely human-written",
        "icon": "Human",
        "detail": (
            "Our analysis found this reads as human-written, with the natural "
            "variation typical of a person's writing. This is an automated estimate "
            "and not a guarantee of authorship."
        ),
    },
}


def generate_label(confidence, verified=False):
    """Return a label dict {attribution, headline, detail, confidence, badge?}.

    When the creator holds a Verified Human Creator certificate, a separate badge is
    attached. The badge is about the creator's verified identity and is visibly
    distinct from the content's transparency label.
    """
    attribution = attribution_for(confidence)
    base = _LABELS[attribution]
    label = {
        "attribution": attribution,
        "headline": f"{base['icon']}: {base['headline']}",
        "detail": base["detail"],
        "confidence": confidence,
    }
    if verified:
        label["badge"] = "Verified Human Creator"
        label["badge_detail"] = (
            "This creator completed human verification. The badge attests to the "
            "creator's verified identity and is separate from the automated "
            "attribution estimate above."
        )
    return label
