"""Detection signals.

Signal 1: Groq LLM classifier (semantic). Returns an AI-likelihood in 0..1 plus a
short rationale. On any error or unparseable response it returns 0.5 so a flaky API
never produces a confident accusation.

Signal 2 (stylometric heuristics) is added in Milestone 4.
"""

import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are a text-attribution analyst. You judge whether a passage was written "
    "by a human or generated by an AI language model. You consider tone, phrasing, "
    "coherence, and how natural or formulaic the writing feels. You are calibrated "
    "and cautious: when a passage is short or genuinely ambiguous, you stay near 0.5 "
    "rather than guessing. Respond with JSON only."
)

_USER_TEMPLATE = (
    "Assess the following text. Return JSON with exactly two keys:\n"
    '  "ai_likelihood": a number from 0.0 (clearly human) to 1.0 (clearly AI)\n'
    '  "rationale": one sentence explaining your judgement\n\n'
    "Text:\n\"\"\"\n{text}\n\"\"\""
)


def _client():
    return Groq(api_key=os.getenv("GROQ_API_KEY"))


def _parse(content):
    """Pull (score, rationale) out of the model reply, tolerating loose JSON.

    Tries strict JSON first, then falls back to regex so a missing quote in the
    rationale does not throw away a perfectly good ai_likelihood number.
    """
    try:
        data = json.loads(content)
        score = max(0.0, min(1.0, float(data["ai_likelihood"])))
        return score, str(data.get("rationale", "")).strip()
    except Exception:
        pass

    num = re.search(r"ai_likelihood\"?\s*[:=]\s*([0-1](?:\.\d+)?)", content)
    if not num:
        raise ValueError(f"no ai_likelihood found in: {content[:200]}")
    score = max(0.0, min(1.0, float(num.group(1))))
    rat = re.search(r"rationale\"?\s*[:=]\s*\"?(.+?)\"?\s*[}\n]", content, re.S)
    rationale = rat.group(1).strip() if rat else ""
    return score, rationale


def llm_signal(text):
    """Return (llm_score, rationale). llm_score is AI-likelihood in 0..1."""
    try:
        resp = _client().chat.completions.create(
            model=_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_TEMPLATE.format(text=text)},
            ],
            temperature=0,
        )
        return _parse(resp.choices[0].message.content)
    except Exception as exc:
        return 0.5, f"signal unavailable, defaulted to uncertain ({exc})"


# --- Signal 2: stylometric heuristics (structural) ---------------------------

_WORD_RE = re.compile(r"[A-Za-z']+")
_SENT_RE = re.compile(r"[.!?]+")
_PUNCT_RE = re.compile(r"[,.;:!?\"'()\-]")


def _clamp(x):
    return max(0.0, min(1.0, x))


def stylo_signal(text):
    """Return (stylo_score, details). stylo_score is AI-likelihood in 0..1.

    Three sub-scores (1 = AI-like), weighted as in planning.md:
      burstiness  std-dev of sentence lengths   low variance reads AI
      diversity   type-token ratio              very high reads AI
      punctuation marks per word                clusters mid (~0.12) reads AI

    Texts under three sentences are low-evidence, so the raw score is blended
    halfway toward 0.5 rather than asserting a structural verdict.
    """
    sentences = [s for s in _SENT_RE.split(text) if s.strip()]
    words = _WORD_RE.findall(text.lower())
    total_words = len(words)

    if total_words == 0:
        return 0.5, {"note": "no words to analyze"}

    sent_lengths = [len(_WORD_RE.findall(s)) for s in sentences] or [total_words]
    stdev = statistics.pstdev(sent_lengths) if len(sent_lengths) > 1 else 0.0
    ttr = len(set(words)) / total_words
    punct_density = len(_PUNCT_RE.findall(text)) / total_words

    sub_burstiness = _clamp((8 - stdev) / 8)
    sub_diversity = _clamp((ttr - 0.45) / 0.30)
    sub_punct = _clamp(1 - abs(punct_density - 0.12) / 0.12)

    raw = 0.5 * sub_burstiness + 0.3 * sub_diversity + 0.2 * sub_punct

    low_evidence = len(sentences) < 3
    score = (raw + 0.5) / 2 if low_evidence else raw

    details = {
        "sentence_count": len(sentences),
        "word_count": total_words,
        "sentence_length_stdev": round(stdev, 3),
        "type_token_ratio": round(ttr, 3),
        "punctuation_density": round(punct_density, 3),
        "sub_burstiness": round(sub_burstiness, 3),
        "sub_diversity": round(sub_diversity, 3),
        "sub_punctuation": round(sub_punct, 3),
        "raw_score": round(raw, 3),
        "low_evidence": low_evidence,
    }
    return round(score, 3), details


# --- Signal 3: lexical AI-marker density (ensemble stretch) -------------------

# Formulaic phrases and transitions that show up disproportionately in AI prose.
_AI_MARKERS = [
    "it is important to note",
    "it's important to note",
    "it is worth noting",
    "in conclusion",
    "in summary",
    "furthermore",
    "moreover",
    "additionally",
    "paradigm shift",
    "delve",
    "navigate the complexities",
    "in today's",
    "plays a crucial role",
    "plays a significant role",
    "a testament to",
    "in the realm of",
    "tapestry",
    "underscores",
    "multifaceted",
    "stakeholders",
    "leverage",
    "seamless",
    "ever-evolving",
    "landscape",
    "foster",
    "holistic",
    "transformative",
    "robust",
    "it is essential to",
    "equally essential",
    "responsible deployment",
]


def lexical_signal(text):
    """Return (lexical_score, details). Score is AI-likelihood in 0..1.

    Counts AI-marker phrases. Absence of markers is weak evidence of a human, so a
    clean text floors at 0.2 rather than 0; each marker adds 0.2 up to 1.0.
    """
    low = text.lower()
    hits = [m for m in _AI_MARKERS if m in low]
    score = _clamp(0.2 + 0.2 * len(hits))
    return round(score, 3), {"marker_hits": len(hits), "markers": hits}


# --- Multimodal: image-metadata signal (stretch) -----------------------------

_AI_IMAGE_TOOLS = [
    "stable diffusion",
    "midjourney",
    "dall-e",
    "dalle",
    "dall e",
    "firefly",
    "imagen",
    "flux",
    "leonardo",
    "nightcafe",
    "gan",
]


def metadata_signal(metadata):
    """Return (meta_score, details) for image metadata. AI-likelihood in 0..1.

    metadata: {caption, software, camera_make, has_exif}
      - a known AI-generator software tag reads as AI
      - a real camera make with EXIF reads as authentic
      - missing EXIF and no camera leans AI, but only weakly
    """
    software = (metadata.get("software") or "").lower()
    camera_make = (metadata.get("camera_make") or "").strip()
    has_exif = bool(metadata.get("has_exif"))

    if any(tool in software for tool in _AI_IMAGE_TOOLS):
        score, reason = 0.95, f"AI generator tag in software: {software}"
    elif camera_make and has_exif:
        score, reason = 0.1, f"real camera EXIF present: {camera_make}"
    elif not has_exif and not camera_make:
        score, reason = 0.65, "no camera make and no EXIF"
    else:
        score, reason = 0.5, "mixed or incomplete metadata"

    return score, {
        "software": software or None,
        "camera_make": camera_make or None,
        "has_exif": has_exif,
        "reason": reason,
    }
