"""Detection signals.

Signal 1: Groq LLM classifier (semantic). Returns an AI-likelihood in 0..1 plus a
short rationale. On any error or unparseable response it returns 0.5 so a flaky API
never produces a confident accusation.

Signal 2 (stylometric heuristics) is added in Milestone 4.
"""

import json
import os
import re

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are a text-attribution analyst. You judge whether a passage was written "
    "by a human or generated by an AI language model. You consider tone, phrasing, "
    "coherence, and how natural or formulaic the writing feels. You are calibrated "
    "and cautious: when a passage is short or genuinely ambiguous, you stay near 0.5 "
    "rather than guessing. Respond with JSON only."
)

_USER_TEMPLATE = (
    "Assess the following text. Return JSON with exactly two keys:\n"
    '  "ai_likelihood": a number from 0.0 (clearly human) to 1.0 (clearly AI)\n'
    '  "rationale": one sentence explaining your judgement\n\n'
    "Text:\n\"\"\"\n{text}\n\"\"\""
)


def _client():
    return Groq(api_key=os.getenv("GROQ_API_KEY"))


def _parse(content):
    """Pull (score, rationale) out of the model reply, tolerating loose JSON.

    Tries strict JSON first, then falls back to regex so a missing quote in the
    rationale does not throw away a perfectly good ai_likelihood number.
    """
    try:
        data = json.loads(content)
        score = max(0.0, min(1.0, float(data["ai_likelihood"])))
        return score, str(data.get("rationale", "")).strip()
    except Exception:
        pass

    num = re.search(r"ai_likelihood\"?\s*[:=]\s*([0-1](?:\.\d+)?)", content)
    if not num:
        raise ValueError(f"no ai_likelihood found in: {content[:200]}")
    score = max(0.0, min(1.0, float(num.group(1))))
    rat = re.search(r"rationale\"?\s*[:=]\s*\"?(.+?)\"?\s*[}\n]", content, re.S)
    rationale = rat.group(1).strip() if rat else ""
    return score, rationale


def llm_signal(text):
    """Return (llm_score, rationale). llm_score is AI-likelihood in 0..1."""
    try:
        resp = _client().chat.completions.create(
            model=_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_TEMPLATE.format(text=text)},
            ],
            temperature=0,
        )
        return _parse(resp.choices[0].message.content)
    except Exception as exc:
        return 0.5, f"signal unavailable, defaulted to uncertain ({exc})"
